// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: any.proto

package per.bmy.NIO.PB.HelloWorld;

public final class AnyOuterClass {
    private AnyOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface AnyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:PB.Any)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string type_url = 1;</code>
         */
        java.lang.String getTypeUrl();

        /**
         * <code>string type_url = 1;</code>
         */
        com.google.protobuf.ByteString
        getTypeUrlBytes();

        /**
         * <code>bytes value = 2;</code>
         */
        com.google.protobuf.ByteString getValue();
    }

    /**
     * Protobuf type {@code PB.Any}
     */
    public static final class Any extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:PB.Any)
            AnyOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Any.newBuilder() to construct.
        private Any(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Any() {
            typeUrl_ = "";
            value_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Any(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            typeUrl_ = s;
                            break;
                        }
                        case 18: {

                            value_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return AnyOuterClass.internal_static_PB_Any_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return AnyOuterClass.internal_static_PB_Any_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            AnyOuterClass.Any.class, AnyOuterClass.Any.Builder.class);
        }

        public static final int TYPE_URL_FIELD_NUMBER = 1;
        private volatile java.lang.Object typeUrl_;

        /**
         * <code>string type_url = 1;</code>
         */
        public java.lang.String getTypeUrl() {
            java.lang.Object ref = typeUrl_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                typeUrl_ = s;
                return s;
            }
        }

        /**
         * <code>string type_url = 1;</code>
         */
        public com.google.protobuf.ByteString
        getTypeUrlBytes() {
            java.lang.Object ref = typeUrl_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                typeUrl_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int VALUE_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString value_;

        /**
         * <code>bytes value = 2;</code>
         */
        public com.google.protobuf.ByteString getValue() {
            return value_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getTypeUrlBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, typeUrl_);
            }
            if (!value_.isEmpty()) {
                output.writeBytes(2, value_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getTypeUrlBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, typeUrl_);
            }
            if (!value_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, value_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof AnyOuterClass.Any)) {
                return super.equals(obj);
            }
            AnyOuterClass.Any other = (AnyOuterClass.Any) obj;

            boolean result = true;
            result = result && getTypeUrl()
                    .equals(other.getTypeUrl());
            result = result && getValue()
                    .equals(other.getValue());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TYPE_URL_FIELD_NUMBER;
            hash = (53 * hash) + getTypeUrl().hashCode();
            hash = (37 * hash) + VALUE_FIELD_NUMBER;
            hash = (53 * hash) + getValue().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static AnyOuterClass.Any parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AnyOuterClass.Any parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AnyOuterClass.Any parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AnyOuterClass.Any parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AnyOuterClass.Any parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AnyOuterClass.Any parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AnyOuterClass.Any parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static AnyOuterClass.Any parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static AnyOuterClass.Any parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static AnyOuterClass.Any parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static AnyOuterClass.Any parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static AnyOuterClass.Any parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(AnyOuterClass.Any prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code PB.Any}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:PB.Any)
                AnyOuterClass.AnyOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return AnyOuterClass.internal_static_PB_Any_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return AnyOuterClass.internal_static_PB_Any_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                AnyOuterClass.Any.class, AnyOuterClass.Any.Builder.class);
            }

            // Construct using NIO.PB.HelloWorld.AnyOuterClass.Any.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                typeUrl_ = "";

                value_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return AnyOuterClass.internal_static_PB_Any_descriptor;
            }

            @java.lang.Override
            public AnyOuterClass.Any getDefaultInstanceForType() {
                return AnyOuterClass.Any.getDefaultInstance();
            }

            @java.lang.Override
            public AnyOuterClass.Any build() {
                AnyOuterClass.Any result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public AnyOuterClass.Any buildPartial() {
                AnyOuterClass.Any result = new AnyOuterClass.Any(this);
                result.typeUrl_ = typeUrl_;
                result.value_ = value_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof AnyOuterClass.Any) {
                    return mergeFrom((AnyOuterClass.Any) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(AnyOuterClass.Any other) {
                if (other == AnyOuterClass.Any.getDefaultInstance()) return this;
                if (!other.getTypeUrl().isEmpty()) {
                    typeUrl_ = other.typeUrl_;
                    onChanged();
                }
                if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
                    setValue(other.getValue());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                AnyOuterClass.Any parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (AnyOuterClass.Any) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object typeUrl_ = "";

            /**
             * <code>string type_url = 1;</code>
             */
            public java.lang.String getTypeUrl() {
                java.lang.Object ref = typeUrl_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    typeUrl_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string type_url = 1;</code>
             */
            public com.google.protobuf.ByteString
            getTypeUrlBytes() {
                java.lang.Object ref = typeUrl_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    typeUrl_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string type_url = 1;</code>
             */
            public Builder setTypeUrl(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                typeUrl_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string type_url = 1;</code>
             */
            public Builder clearTypeUrl() {

                typeUrl_ = getDefaultInstance().getTypeUrl();
                onChanged();
                return this;
            }

            /**
             * <code>string type_url = 1;</code>
             */
            public Builder setTypeUrlBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                typeUrl_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes value = 2;</code>
             */
            public com.google.protobuf.ByteString getValue() {
                return value_;
            }

            /**
             * <code>bytes value = 2;</code>
             */
            public Builder setValue(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                value_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes value = 2;</code>
             */
            public Builder clearValue() {

                value_ = getDefaultInstance().getValue();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:PB.Any)
        }

        // @@protoc_insertion_point(class_scope:PB.Any)
        private static final AnyOuterClass.Any DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new AnyOuterClass.Any();
        }

        public static AnyOuterClass.Any getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Any>
                PARSER = new com.google.protobuf.AbstractParser<Any>() {
            @java.lang.Override
            public Any parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Any(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Any> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Any> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public AnyOuterClass.Any getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PB_Any_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_PB_Any_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\tany.proto\022\002PB\"&\n\003Any\022\020\n\010type_url\030\001 \001(\t" +
                        "\022\r\n\005value\030\002 \001(\014B<\n\021NIO.PB.HelloWorldP\000\242\002" +
                        "\003GPB\252\002\036Google.Protobuf.WellKnownTypesb\006p" +
                        "roto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_PB_Any_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_PB_Any_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_PB_Any_descriptor,
                new java.lang.String[]{"TypeUrl", "Value",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
